# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bquery.proto\x12\x05query\"\x1b\n\x0cQueryRequest\x12\x0b\n\x03sql\x18\x01 \x01(\t\"J\n\rQueryResponse\x12\x13\n\x0bresult_json\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\"$\n\x0fSubQueryRequest\x12\x11\n\tquery_sql\x18\x01 \x01(\t\"$\n\rPartialResult\x12\x13\n\x0bresult_json\x18\x01 \x01(\t2J\n\rMasterService\x12\x39\n\x0c\x45xecuteQuery\x12\x13.query.QueryRequest\x1a\x14.query.QueryResponse2O\n\x0cQueryService\x12?\n\x0f\x45xecuteSubQuery\x12\x16.query.SubQueryRequest\x1a\x14.query.PartialResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYREQUEST']._serialized_start=22
  _globals['_QUERYREQUEST']._serialized_end=49
  _globals['_QUERYRESPONSE']._serialized_start=51
  _globals['_QUERYRESPONSE']._serialized_end=125
  _globals['_SUBQUERYREQUEST']._serialized_start=127
  _globals['_SUBQUERYREQUEST']._serialized_end=163
  _globals['_PARTIALRESULT']._serialized_start=165
  _globals['_PARTIALRESULT']._serialized_end=201
  _globals['_MASTERSERVICE']._serialized_start=203
  _globals['_MASTERSERVICE']._serialized_end=277
  _globals['_QUERYSERVICE']._serialized_start=279
  _globals['_QUERYSERVICE']._serialized_end=358
# @@protoc_insertion_point(module_scope)
