# Start with an official Python runtime.
FROM python:3.12-slim

WORKDIR /app

# Add the protos directory to the Python path
ENV PYTHONPATH "${PYTHONPATH}:/app:/app/protos"

COPY worker/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire protos package into the container
COPY protos/ /app/protos

# Copy the worker's source code
COPY worker/main.py .
# The gRPC server will listen on this port inside the container.
EXPOSE 50051

CMD ["python", "main.py"]